### ISSUE TITLE
Using this plugin for optimized route between multiple addresses

### ISSUE THREAD

**Issue by brandonjjon** [dereuromark/cakephp-geo#11]
Hi there,

I'd like to send google a start address, list of addresses, and an end point and then get a return array of the optimized route.. is this possible with this plugin?

Can't wait for the documentation to be complete :) From what I can see so far, this is a great plugin.

Thanks.

**Comment by dereuromark** [comment]
You would need to go to googles documentation on if this is in general possible.
This CakePHP optimized code is mainly geocoding a single address right now, or display a numeric amount of geolocations via googlemaps map.

Feel free to give me a hand regarding missing docs or code, though.

**Comment by brandonjjon** [comment]
I actually found something that might work for me instead. It's called RouteXL and they provide free route optimization on up to 20 addresses. They have a demo php class as well so I'll give that a shot.

Thanks

**Comment by dereuromark** [comment]
Yes that is possible.
