### ISSUE TITLE
Undefined index: accuracy

### ISSUE THREAD

**Issue by mikedigital** [dereuromark/cakephp-geo#13]
This is a little strange. I'm querying for an address and within the _process method, I'm retrieving a result which is, for some reason, showing up as an invalid result (```valid_results = false```) and in doing so, my seemingly valid/invalid result isn't providing the accuracy index on line 417 of the Geocode.php class.
```php
if ($this->_isNotAccurateEnough($this->result['accuracy'])) {
```

So that I can be extra annoying but potentially helpful, here is my full response:
```php
$result = [
	'results' => [
		(int) 0 => [
			'formatted_address' => '304 Elmwood Ave, Buffalo, NY 14222, USA',
			'country' => 'United States',
			'country_code' => 'US',
			'country_province' => 'New York',
			'country_province_code' => 'NY',
			'postal_code' => '14222',
			'locality' => 'Buffalo',
			'sublocality' => '',
			'route' => 'Elmwood Avenue 304',
			'types' => [
				[maximum depth reached]
			],
			'lat' => (float) 42.9052435,
			'lng' => (float) -78.8775244,
			'location_type' => 'ROOFTOP',
			'viewport' => [
				[maximum depth reached]
			],
			'bounds' => [
				[maximum depth reached]
			],
			'address_components' => [
				[maximum depth reached]
			],
			'valid_type' => false,
			'accuracy' => (int) 7,
			'accuracy_name' => 'route'
		]
	],
	'status' => 'OK'
]
```

**Comment by dereuromark** [comment]
Probably needs a check.
Are you able to provide a PR with a fix?

**Comment by dereuromark** [comment]
Fixed, and branch moved to `3.x-lecagy`.
I will soon merge develop into master and release the first official 3.x version with an improved API.
