### ISSUE TITLE
Im new to using cakephp 3 and googlemaps

### ISSUE THREAD

**Issue by savagegrave** [dereuromark/cakephp-geo#18]
Good evening Mark,

Im trying to use your googlemaps helper to insert a map and then place markers onto it using lat and lng from an outsourced xml feed and not from a database.

Ive followed the examples in your documents but cant get the helper to load without using the $config variable.

I know its probably my ignorance within lack of knowledge however from the list of config options you have set out I cant see any reason to change from the default.

when I use `$this->loadHelper('Geo.GoogleMap', $config);` all I get from the website is the following error,

> Argument 2 passed to Cake\View\View::loadHelper() must be of the type array, null given, called in /home/airnexvi/public_html/src/Template/Airoperations/fleetview.ctp on line 2

**Comment by dereuromark** [comment]
So $config is actually null?
Please also see the existing test cases and the demo implementation in the sandbox.

**Comment by savagegrave** [comment]
yep $config is null so I have removed it from the loadhelper command.

However even if I do create the config array no map actually appears. When I "inspect" the area it should be, chrome tells me the following....

> Uncaught ReferenceError: google is not defined

Sorry for my ignorance

**Comment by dereuromark** [comment]
This is not a bug in the plugin, you must understand how to use it from the resources available.
There are quite a bunch of them, please refer to those.
