### ISSUE TITLE
GoogleMap helper $options not correct

### ISSUE THREAD

**Issue by feldmarv** [dereuromark/cakephp-geo#20]
For example the $option for zoom is not exposed correctly in javascript. The following configuration in php is wrong in javascript variable myOptions. Es I can see the variable myOptions does never change its parameters.

```
            $options = [
                'zoom' => 15,
                'type' => 'R',
                'geolocate' => true,
                'div' => ['id' => 'someothers'],
                'map' => [
                    'navOptions' => ['style' => 'SMALL'],
                    'typeOptions' => ['style' => 'HORIZONTAL_BAR', 'pos' => 'RIGHT_CENTER']]
            ];

            $map = $this->GoogleMap->map($options);
```

`var myOptions = {zoom: 5, streetViewControl: false, navigationControl: true, mapTypeControl: true, scaleControl: true, scrollwheel: false, keyboardShortcuts: true, center: initialLocation, navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL}, mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.HORIZONTAL_BAR, position: google.maps.ControlPosition.RIGHT_CENTER}, mapTypeId: google.maps.MapTypeId.ROADMAP};
`

**Comment by dereuromark** [comment]
Well, if you look into the code, the zoom can only be set via default options this way.
Otherwise it is part of the "map" array:

    'map' => [
        'zoom' => 15,
        'navOptions' => ['style' => 'SMALL'],
        ...
    ]

**Comment by feldmarv** [comment]
But if I look into the documentation, its should also work via default options.
https://github.com/dereuromark/cakephp-geo/blob/master/docs/Helper/GoogleMap.md

Thanks in advance!

**Comment by dereuromark** [comment]
You are right, that might have gone lost during the 3.x upgrade.
Can you please check https://github.com/dereuromark/cakephp-geo/commit/a5a908d0074325b8453529fd4b0c2e5b9e916e06 if it fixes it for you?
I also added a regression test now.

**Comment by dereuromark** [comment]
Can I release/tag a new version then?

**Comment by feldmarv** [comment]
Yes please!
