### ISSUE TITLE
How to catch invalid address in behavior

### ISSUE THREAD

**Issue by feldmarv** [dereuromark/cakephp-geo#21]
When saving an address with invalid data there is an sql error because lat/lng cannot be processed. How to catch this problem?

Thanks in advance!

`Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) * COS(((RADIANS((Matches.lng)) - RADIANS())))) + (SIN((((PI() / 2) - RADIANS(' at line 1`

**Comment by dereuromark** [comment]
You need to pass a bit more info. Cake version, plugin version and maybe some details on how to reproduce.
Also, what is the entity data when saving before and after calling the behavior?

**Comment by feldmarv** [comment]
CakePHP Version: 3.3.*
CakePHP-Geo Version: ^1.0

Ah just saw its not the behavior that breaks its the empty lat/lnt field. So its not a bug.
