### ISSUE TITLE
staticMap method does not use globally configured Google API key

### ISSUE THREAD

**Issue by fredhamster** [dereuromark/cakephp-geo#22]
I just wanted to display a static map and found that the map image never showed up.  Looking at the image URL, I saw that no API key was being added (and Google was telling me that the API key is required; when I added the key manually, the static image URL worked).  I debugged around and proved to myself that my key was actually getting loaded properly from the GoogleMap index of the configuration array.  Eventually I determined that, although apiUrl() adds the key as expected, only map() calls that and not staticMap().  Since apiUrl didn't seem directly usable by staticMapUrl, I patched staticMapUrl to also add the API key.  This at least gets the staticMap calls working as expected.
Here is a diff for the modified code.  Not sure this is the optimal solution, since I only added the key   configuration processing code from apiUrl into the staticMapUrl function.

--------------

[cakephp-geo-fix-staticmap-api-key.patch.txt](https://github.com/dereuromark/cakephp-geo/files/972134/cakephp-geo-fix-staticmap-api-key.patch.txt)

**Comment by dereuromark** [comment]
Are you able to Provide a PR ? Otherwise i try to fix it from your diff.

**Comment by fredhamster** [comment]
Yes, I think.  I have dropped the original git diff output and replaced it with a patch file.

**Comment by dereuromark** [comment]
A Pull request would always be the preferred way, since that can easily be merged and published.
I will try to use your patch, however.

**Comment by dereuromark** [comment]
Commited in https://github.com/dereuromark/cakephp-geo/commit/5413b12422a7207d71b9f76278e0b67563aee7ca
