### ISSUE TITLE
entities doesn't save when adress fields are empty

### ISSUE THREAD

**Issue by cyberbobjr** [dereuromark/cakephp-geo#24]
Hi,
if i set adress fields optionals, and i want to add a new Entity without adress, the geodecoder behavior invalidate the entities and the save event is cancelled.

for fixing this, change this line in GeocoderBehavior.php :

```
        if ($search === '') {
            return NULL;
        }
```

to 

```
        if ($search === '' && !$this->_config['allowEmpty']) {
            return NULL;
        }

```

**Comment by dereuromark** [comment]
Resolved with https://github.com/dereuromark/cakephp-geo/pull/25
