### ISSUE TITLE
Link to missing page in docs.

### ISSUE THREAD

**Issue by ADmad** [dereuromark/cakephp-geo#26]
`docs/README.md` has link `Search plugin integration` to URL `https://github.com/dereuromark/cakephp-geo/blob/master/docs/Geocoder/Search.md` which doesn't exist.

**Comment by dereuromark** [comment]
Thx
Resolved with https://github.com/dereuromark/cakephp-geo/commit/324de4b48244579df1933e2f5b34428fa973ee0a for the time being until someone can write a new FOC Search one.
