### ISSUE TITLE
Error in Documentation of Geocoder Library?

### ISSUE THREAD

**Issue by cewi** [dereuromark/cakephp-geo#28]
Hi,

I set up Geocoder library as described here:
https://github.com/dereuromark/cakephp-geo/blob/master/docs/Geocoder/Geocoder.md 

My code in app.php:
```
    'Geocoder' => [
        'provider' => '\Geocoder\Provider\OpenStreetMap',
    ],
```
My code in a controller:
```
...
$this->Geocoder = new \Geo\Geocoder\Geocoder();
$this->Geocoder->setOptions([
                'allowInconclusive' => true,
                'minAccuracy' => Geocoder::TYPE_POSTAL]);
...
```

This throws an Error:
> Call to undefined method Geo\Geocoder\Geocoder::setOptions() 

Looking at the code in 
https://github.com/dereuromark/cakephp-geo/blob/master/src/Geocoder/Geocoder.php, there is no setOptions() method.

Passing the options instead to the constructor works as expected. Is there an error in the docs or are there mistakes in my setup?

**Comment by dereuromark** [comment]
You are right, this seems to be some copy and paste issue
Does https://github.com/dereuromark/cakephp-geo/commit/ec6d38d49e5014fd2b968e468433514bb348730d fix things?
Otherwise please free to PR any docs fixes you find necessary.
Thank you.

**Comment by cewi** [comment]
That's perfect. Thank you!
