### ISSUE TITLE
Google Map Helper doesn't go directly to marker point

### ISSUE THREAD

**Issue by Rainyer** [dereuromark/cakephp-geo#31]
Hi, first of all thanks for this awesome plugin! It has helped me a lot in a project.
I think it's more a doubt than a issue. When I set a marker and render the map, my map doesn't render at the marker location, for example I set a marker to Brazil, and when the map renders it is positioned at Europe. The marker is in it's correct place, but we need to drag the map to Brazil to see it. Is there any config to auto positioning the map?

**Comment by dereuromark** [comment]
you can set the center in the config, also also pass this config dynamically to the helper.
https://github.com/dereuromark/cakephp-geo/blob/master/src/View/Helper/GoogleMapHelper.php#L166-L167

**Comment by Rainyer** [comment]
Oh, I see. Thank you very much for that!

**Comment by Rainyer** [comment]
Oh, I see. Thank you very much for that!
