### ISSUE TITLE
Upgrade to willdurand/geocoder 4.x

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-geo#32]
This requires some major refactoring probably...

**Comment by chopstik** [comment]
I've not dived too deep but do you have an idea of the amount of refactoring reqd? I've two codebases (one non-Cake) sharing the same composer.json and composer is complaining when i want to require another package that requires ^4.x.

**Comment by dereuromark** [comment]
Definitely BC breaking.
But I think the refactoring is medium. 
Feel free to provide a basic branch as PR - and I can then help finishing it.

**Comment by dereuromark** [comment]
Refs https://github.com/geocoder-php/Geocoder/pull/1032

**Comment by dereuromark** [comment]
Current outdated packages:

  - egeloen/http-adapter (0.8.0) latest is 1.0.2
  - willdurand/geocoder (v3.3.2) latest is 4.2.1
