### ISSUE TITLE
How do I invalidate if address cannot be geocoded?

### ISSUE THREAD

**Issue by kevindecapite** [dereuromark/cakephp-geo#35]
I tried configuring the behavior with `'on' => 'beforeMarshal'` and then setup a validation rule like:

```
$validator
            ->isArray('geocoder_result')
            ->requirePresence('geocoder_result')
            ->notEmpty('geocoder_result');
```

When I debug the entity after running patchEntity(), the value of geocoder_result is `'geocoder_result' => '""'`, and this is for a correct address.

If I use a bad address, then geocoder_result property doesn't even exist.

**Comment by dereuromark** [comment]
Sounds like this could work.

**Comment by kevindecapite** [comment]
Thanks for responding. Basically my validation isn't working because even with a properly geocoded address, the geocoder_result field is still marked as invalid. What would be the appropriate way to check that the address was geocoded?

**Comment by dereuromark** [comment]
Make sure that the data is there before validation is triggered.
Also make sure that https://github.com/dereuromark/cakephp-geo/blob/master/src/Model/Behavior/GeocoderBehavior.php#L53 does not interfere.
If you get an address back with less minAccuracy then it will also invalidate.

PS: Usually the last even is enough. So extra rule required IMO.

**Comment by kevindecapite** [comment]
I don't understand what your comments mean, but I was able to make validation work using the following rules in my table which uses the behavior:

```
$validator
            ->range('lat', [-90, 90])
            ->requirePresence('lat');

        $validator
            ->range('lng', [-180, 180])
            ->requirePresence('lng');
```

Note that the `requirePresence` is needed as I noticed the behavior will not include those properties in the entity if geocoding fails. So I can't check for `notEmpty`.

Also, this requires that I use `'on' => 'beforeMarshal'` in the behavior's configuration so the entity properties `lat` & `lng` appear in the entity before validation rules are engaged.

I really love this behavior but as I'm very new to Cake 3 I'm finding certain things about its implementation a bit confusing! Thank you for your quick replies :-)

**Comment by dereuromark** [comment]
I appreciate your your feedback!
If there is anything in documentation to help or improve here, I am glad for any pull requests that clarify things.

**Comment by kevindecapite** [comment]
When I have some time, I would love to contribute. I will be in touch.

**Comment by dereuromark** [comment]
All righty, closing then.
