### ISSUE TITLE
Generated map not accessible outside of jquery ready?

### ISSUE THREAD

**Issue by lamasgergo** [dereuromark/cakephp-geo#42]
Sometime you need to use map after the helper generated it. Now all maps generated into a local variable. jQuery(document).ready(function() { var map0 = .... }); 

For examle if you would like to modify on the map object you have no acces for it, haven't you?

Maybe it would great to fire a jquery event after the map was generated, so you can catch the event and if the event contains the generated map object you can do anyting wit that map after.

or simple make the map object globally :) without "var"

Am I wrong? We would like to use clusterer or router box.

**Comment by dereuromark** [comment]
See https://github.com/dereuromark/cakephp-geo/blob/master/src/View/Helper/GoogleMapHelper.php#L959
You can inject any JS into it to access it then from there.

But if you can find another way, let me know.

**Comment by lamasgergo** [comment]
@dereuromark Thanks for answer, i will try it out, i havent seen this function but i think it's enoug. i'm closing :)
