### ISSUE TITLE
Use of cake3-branch results in deprecation errors

### ISSUE THREAD

**Issue by sintsmeding** [dereuromark/cakephp-geo#54]
First let me thank you for keeping this plugin available for both CakePHP 3.x and 4.x.

Unfortunately, it seems impossible to use the CakePHP Geo Plugin within CakePHP 3.x-applications without deprecation errors being thrown out.

CakePHP Geo for CakePHP 3 (aka CakePHP Geo 1.x) requires willdurand/geocoder ^3.3.
willdurand/geocoder ^3.3 requires egeloen/http-adapter ~0.8.

The Ivory Http Adapter was abandoned and is no longer maintained. Unfortunately this dependency is causing deprecated errors since some things have been moved around within CakePHP. Mainly their CakeHttpAdapter not using the new function naming and namespaces of the Request and Response objects within CakePHP.

egeloen/http-adapter suggests php-http/httplug as an alternative.

I've tried configuring CakePHP Geo to use httplug and also the http-adapter within CakePHP. Unfortunately, version 3.3 of willdurand/geocoder explicitly expects egeloen/http-adapter-objects as parameters and/or return values. I was not able to get the Google Maps provider working with a different http adapter than the default one.

The issue of depending on Ivory Http Adapter has been fixed in Geocoder 4.x.
Sadly this version of Geocoder is not supported by the Cake3/1.x branch of CakePHP Geo.

Of course we could turn of deprecation warnings in PHP, but this is not very eligible. Their cause would remain and will cause real problems if these deprecation warnings by any means turn into real errors.

Of course upgrading to Cake 4.x solves these issues. But at the moment Cake 3.x is still supported, as is CakePHP Geo for CakePHP 3.x. Having to refactor entire applications to CakePHP 4.x in very short time just because we're not able to replace some third party adapter would be a bit silly.

Is there any chance there will be a version of CakePHP Geo for CakePHP 3.x that works together with Geocoder 4.x?

If anyone knows an alternative workaround for just ignoring the deprecation messages that would be highly appreciated as well.

**Comment by sintsmeding** [comment]
Clarification:

Yes, this issue is similar to this one, but only partially:
https://github.com/dereuromark/cakephp-geo/issues/46

The deprecations within CakePHP Geo were indeed fixed in August/September last year, but the deprecations caused by egeloen/http-adapter/src/CakeHttpAdapter.php remained.

**Comment by dereuromark** [comment]
Feel free to make a PR that accomplishes this.
I cannot spend any time on this myself right now.
If there is a BC break we could probably try to release as a minor with a warning in the changelog.

Current (easy) workaround is to silence and ignore deprecation messages on outdated majors (3.x).
I would recommend that approach.
