### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by rochamarcelo** [dereuromark/cakephp-geo#56]
Geocoder is trying to use unavailable classes 
```
$this->adapter = new $adapterClass(new HttpCakeClient(), new ResponseFactory());
``` 
Both Http\Adapter\Cake\Client and Http\Message\ResponseFactory are not available.

It seems installation doc is outdated. What are the correct steps to install and use the plugin?

**Comment by dereuromark** [comment]
You need to decide on what kind of engine you want to use.
I use for example google maps

        "php-http/cakephp-adapter": "0.3.x-dev",
        "php-http/message": "^1.8.0"

**Comment by dereuromark** [comment]
I added a note in https://github.com/dereuromark/cakephp-geo/blob/master/docs/Install.md#optional-packages
Let me know if that clears it up.

**Comment by rochamarcelo** [comment]
Thank you.
