### ISSUE TITLE
Class 'Geocoder\Provider\GoogleMaps\GoogleMaps' not found

### ISSUE THREAD

**Issue by doonot** [dereuromark/cakephp-geo#57]
Hi

We are trying to upgrade to CakePHP 4 and ran into this issue:

`Error: Class 'Geocoder\Provider\GoogleMaps\GoogleMaps' not found in .../vendor/dereuromark/cakephp-geo/src/Geocoder/Geocoder.php:306`

Also it looks like `StatefulGeocoder` is also not defined.

What are we doing wrong?

Thanks and regards,
Patrick

**Comment by dereuromark** [comment]
Please see https://github.com/dereuromark/cakephp-geo/blob/master/docs/Install.md#optional-packages

**Comment by doonot** [comment]
Both of them are installed. 

`"php-http/cakephp-adapter": "^0.3.0",
  "php-http/message": "^1.8.0"`

This fixed the issue with the HttpCakeClient but I am not able to fix the error above.

**Comment by dereuromark** [comment]
You didnt install the geocoder, read that sentence again

Also see e.g.
https://github.com/dereuromark/cakephp-sandbox/blob/master/composer.json#L68-L69

Maybe https://github.com/dereuromark/cakephp-geo/blob/master/docs/Behavior/Geocoder.md#configure-your-own-geocoder needs a bit more explicit note on how to include that library.

**Comment by dereuromark** [comment]
I updated that paragraph of optional packages to include also the concrete adapter requirements.
