### ISSUE TITLE
Define API key during runtime

### ISSUE THREAD

**Issue by doonot** [dereuromark/cakephp-geo#58]
Hi

We would like to be able to define the API key during runtime, so each user can add his own Google API key (since we are a platform, our Google API invoice is getting bigger and bigger). Is there any way to do this?

Thank you very much.
Patrick

**Comment by dereuromark** [comment]
Why wouldnt that work?
just use the key at that time when creating the objects, if necessary you can write to Configure at runtime as well.

**Comment by doonot** [comment]
Thanks for your answer. Currently in order to know which user performed the request, we need to have access to the JWT. This works in the controllers but the behaviour is defined in the initialize-method of the table. There we don't have any reference to the user who performed the request. We can access the config file, but the Google API key is stored in the database.

**Comment by dereuromark** [comment]
I would then attach the behavior here at runtime :) If that works.
As then you would have the key upon needing it.

**Comment by doonot** [comment]
Do you have an idea how this can be done? We never did that, sorry :)

**Comment by dereuromark** [comment]
In your controller, just before you use it, add 

    $this->ModelName->loadBehavior():

with the configs you need.
If already loaded, you can also unload it before loading it with the right configs needed.

**Comment by doonot** [comment]
Thank you very much, that was very helpful!
