### ISSUE TITLE
Class 'Http\Adapter\Cake\Client' not found

### ISSUE THREAD

**Issue by Modicrumb** [dereuromark/cakephp-geo#59]
Error when using with CakePHP 4.1.7

I'm using the Geocoder behavior in a model and I ran into this error, it looks like it can't find the class in Geocoder.php. Is there a dependency here not being specified? 

The settings I have in the model are 

        $this->addBehavior(
            'Geo.Geocoder',
            [
                'apiKey' => Configure::read('Settings.App.google_maps_api_key'),
                'address' => ['address', 'city', 'zip'],
                'overwrite' => true
            ]
        );

In case it wasn't clear the error I am getting is:
Class 'Http\Adapter\Cake\Client' not found

I've discovered the dependency: https://github.com/php-http/cakephp-adapter

After that however, after requiring it I get a new error: 
Fatal error: Interface 'Http\Message\ResponseFactory' not found in /vagrant/iec/httpdocs/vendor/dereuromark/cakephp-geo/src/Geocoder/ResponseFactory.php on line 8

**Comment by dereuromark** [comment]
Please see install docs
https://github.com/dereuromark/cakephp-geo/blob/master/docs/Install.md#optional-packages

**Comment by Modicrumb** [comment]
Sorry I saw the related issue and realized my mistake @dereuromark thank you kindly
