### ISSUE TITLE
Allow passing `Coordinates` instance to `distance` finder.

### ISSUE THREAD

**Issue by ADmad** [dereuromark/cakephp-geo#60]
Often when using `find('distance')` you have a `Coordinates` instance at hand from an earlier geocoding operation. 

So using 
```
find('distance', ['coordinates ' => $coordinates])
``` 
would require less typing than
```
->find('distance', [
    'lat' => $coordinates->getLatitude(),
    'lng' => $coordinates->getLongitude(),
])
```

**Comment by dereuromark** [comment]
Sounds good.
Probably quite easy to add on top in a BC way, using its own assoc key.

Do you have any specific (value) object in mind? Or do they exist already, preferably with some interface?
PRs welcome

**Comment by ADmad** [comment]
I was proposing using `Geocoder\Model\Coordinates` of the `willdurand/geocoder` packages, which this plugin relies on.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-geo/pull/63
