### ISSUE TITLE
`overwrite` option of GeocodeBehavior is unused.

### ISSUE THREAD

**Issue by ADmad** [dereuromark/cakephp-geo#62]
In CakePHP 2.x compatible version of this plugin if `overwrite` was `false` and entity (model data) already had latitude and longitude fields filled then geocoding was skipped.

This feature allowed users to provide their own values or leave the fields empty in which case the lat-lng was geocoded using the address fields. I need back this behavior in current version of this plugin :slightly_smiling_face:.

**Comment by dereuromark** [comment]
Looks like this was completely dropped for the entity changes.

I wonder if we can add it then just with the opposite default value: overwrite `true`
This way one would have to set it to false until the next major to have this back.

Should this check on the existence of the values? Or dirty() status of the entity field without checking its value?

**Comment by ADmad** [comment]
> Should this check on the existence of the values? Or dirty() status of the entity field without checking its value?

I think both. We need to check if the coordinates are edited and not empty to skip geocoding.

**Comment by dereuromark** [comment]
Do you want to make a PR here?

**Comment by ADmad** [comment]
I have put it on my TODO list, can't say when I will get around to it :slightly_smiling_face:.
