### ISSUE TITLE
Internally use Geocoder PHP lib

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-geo#7]
Use https://github.com/geocoder-php/Geocoder v3 instead of own lib.

**Comment by StephanGeorg** [comment]
+1 ;)

**Comment by dereuromark** [comment]
I started: https://github.com/dereuromark/cakephp-geo/tree/develop
Unfortunately, lot of data is lost when using this library.

Refs https://github.com/geocoder-php/Geocoder/issues/483

**Comment by dereuromark** [comment]
I am not too happy with that dependency yet, it has quite a few flaws.
But I guess it will have to do.
