### ISSUE TITLE
InfoWindows not correct displayed

### ISSUE THREAD

**Issue by cewi** [dereuromark/cakephp-geo#9]
InfoWindows set with GoogleMapsV3Helper->addMarker($option['content]) are now showing only an empty box. When setting $_defaultOptions['map']['api'] to anything below '3.19', i.e. '3.18' in the Helper, or passing an api-Version below 3.19 in the constructor, everything is displayed as expected. Tested on Safari, Firefox 35 and Chrome 40 on Mac. Same with the GoogleMapsV3Helper in the Tools-Plugin for Cake 2. 
Maybe Google changed the API? (My Application worked well for a more than a year and then stopped showing proper InfoWindows, I didn't change any Code)

**Comment by dereuromark** [comment]
That is possible. Any hints in their api docs?

**Comment by cewi** [comment]
The Changelog is here:
https://code.google.com/p/gmaps-api-issues/wiki/JavascriptMapsAPIv3Changelog 
They changed something in the Code for the InfoWindow here: 
https://code.google.com/p/gmaps-api-issues/issues/detail?id=7333

My Infowindows with the current release (3.19) look like this:
![bildschirmfoto 2015-02-20 um 08 14 05](https://cloud.githubusercontent.com/assets/1643900/6282646/aaee92e8-b8d8-11e4-8783-45ba3576a526.png)

When I set the api to i.e. 3.18 It displays correct:
![bildschirmfoto 2015-02-20 um 08 14 38](https://cloud.githubusercontent.com/assets/1643900/6282655/c83169a2-b8d8-11e4-9781-aef1e6f2868e.png)

I use my own Helper which extends your Helper. But that should not be the problem. The code for the function, which sets the marker marker is this (I tested using your helper directly, same result):

    public function addSearch(array $location = null)
        {
           $options['lat'] = $location['lat'];
           $options['lng'] = $location['lng'];
           $options['title'] = 'Ihre Suche';
           $options['icon'] = 12;
           $options['content'] = '<h4>Ausgangspunkt Ihrer Suche:</h4><p>' . $location['formatted_address']'</p>';
           parent::addMarker($options);
       }

**Comment by cewi** [comment]
hmm, a clean new installed app with only your plugin loaded and everything set up like you described here http://www.dereuromark.de/2010/12/21/googlemapsv3-cakephp-helper/ showed a correct InfoWindow. There must be something wrong in my code. But I have no idea why it worked for more than a year. Sorry!
